export const SET_MENU = 'SET_MENU'
export const SET_THEME = 'SET_THEME'
export const SET_COLOR_STYLE = 'SET_COLOR_STYLE'
export const SET_HISTORY_PAGE = 'SET_HISTORY_PAGE'
export const SET_TOKEN = 'SET_TOKEN'
